CREATE TABLE salary
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    salary_type VARCHAR(255),
    hourly_rate FLOAT                                   NOT NULL,
    CONSTRAINT pk_salary PRIMARY KEY (id)
);

ALTER TABLE employee
    ADD birth_country_id BIGINT;

ALTER TABLE employee
    ADD birthday_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE employee
    ADD birthplace VARCHAR(255);

ALTER TABLE employee
    ADD cpam VARCHAR(255);

ALTER TABLE employee
    ADD salary_id BIGINT;

ALTER TABLE employee
    ADD ss_nbr VARCHAR(255);

ALTER TABLE collective_convention
    ADD friday_hours VARCHAR(255);

ALTER TABLE collective_convention
    ADD label VARCHAR(255);

ALTER TABLE collective_convention
    ADD monday_hours VARCHAR(255);

ALTER TABLE collective_convention
    ADD saturday_hours VARCHAR(255);

ALTER TABLE collective_convention
    ADD sunday_hours VARCHAR(255);

ALTER TABLE collective_convention
    ADD thursday_hours VARCHAR(255);

ALTER TABLE collective_convention
    ADD tuesday_hours VARCHAR(255);

ALTER TABLE collective_convention
    ADD wednesday_hours VARCHAR(255);

ALTER TABLE employee
    ADD CONSTRAINT uc_employee_birth_country UNIQUE (birth_country_id);

ALTER TABLE employee
    ADD CONSTRAINT uc_employee_salary UNIQUE (salary_id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_BIRTH_COUNTRY FOREIGN KEY (birth_country_id) REFERENCES country (id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_SALARY FOREIGN KEY (salary_id) REFERENCES salary (id);