CREATE TABLE collective_convention
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                  VARCHAR(255),
    description           VARCHAR(255),
    employment_details_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_collectiveconvention PRIMARY KEY (id)
);

CREATE TABLE company
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255),
    address               VARCHAR(255),
    employment_details_id BIGINT,
    CONSTRAINT pk_company PRIMARY KEY (id)
);

CREATE TABLE department
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                  VARCHAR(255),
    description           VARCHAR(255),
    employment_details_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id)
);

CREATE TABLE employee
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                           VARCHAR(255),
    email                          VARCHAR(255),
    salary                         DOUBLE PRECISION                        NOT NULL,
    company_id                     BIGINT,
    employee_employment_details_id BIGINT,
    CONSTRAINT pk_employee PRIMARY KEY (id)
);

CREATE TABLE employee_employment_details
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employment_category_id       VARCHAR(255),
    employment_positions_id      VARCHAR(255),
    collective_conventions_id    VARCHAR(255),
    employment_qualifications_id VARCHAR(255),
    department_id                VARCHAR(255),
    CONSTRAINT pk_employeeemploymentdetails PRIMARY KEY (id)
);

CREATE TABLE employment_category
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                  VARCHAR(255),
    description           VARCHAR(255),
    employment_details_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_employmentcategory PRIMARY KEY (id)
);

CREATE TABLE employment_details
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_employmentdetails PRIMARY KEY (id)
);

CREATE TABLE employment_position
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                  VARCHAR(255),
    description           VARCHAR(255),
    employment_details_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_employmentposition PRIMARY KEY (id)
);

CREATE TABLE employment_qualification
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                  VARCHAR(255),
    description           VARCHAR(255),
    employment_details_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_employmentqualification PRIMARY KEY (id)
);

ALTER TABLE company
    ADD CONSTRAINT uc_company_employment_details UNIQUE (employment_details_id);

ALTER TABLE employee
    ADD CONSTRAINT uc_employee_employee_employment_details UNIQUE (employee_employment_details_id);

ALTER TABLE collective_convention
    ADD CONSTRAINT FK_COLLECTIVECONVENTION_ON_EMPLOYMENT_DETAILS FOREIGN KEY (employment_details_id) REFERENCES employment_details (id);

ALTER TABLE company
    ADD CONSTRAINT FK_COMPANY_ON_EMPLOYMENT_DETAILS FOREIGN KEY (employment_details_id) REFERENCES employment_details (id);

ALTER TABLE department
    ADD CONSTRAINT FK_DEPARTMENT_ON_EMPLOYMENT_DETAILS FOREIGN KEY (employment_details_id) REFERENCES employment_details (id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_EMPLOYEE_EMPLOYMENT_DETAILS FOREIGN KEY (employee_employment_details_id) REFERENCES employee_employment_details (id);

ALTER TABLE employment_category
    ADD CONSTRAINT FK_EMPLOYMENTCATEGORY_ON_EMPLOYMENT_DETAILS FOREIGN KEY (employment_details_id) REFERENCES employment_details (id);

ALTER TABLE employment_position
    ADD CONSTRAINT FK_EMPLOYMENTPOSITION_ON_EMPLOYMENT_DETAILS FOREIGN KEY (employment_details_id) REFERENCES employment_details (id);

ALTER TABLE employment_qualification
    ADD CONSTRAINT FK_EMPLOYMENTQUALIFICATION_ON_EMPLOYMENT_DETAILS FOREIGN KEY (employment_details_id) REFERENCES employment_details (id);