CREATE TABLE address
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address_one VARCHAR(255),
    address_two VARCHAR(255),
    city        VARCHAR(255),
    province    VARCHAR(255),
    postal_code VARCHAR(255),
    country_id  BIGINT,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE country
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code       VARCHAR(255),
    name       VARCHAR(255),
    company_id BIGINT,
    CONSTRAINT pk_country PRIMARY KEY (id)
);

ALTER TABLE employee
    ADD address_id BIGINT;

ALTER TABLE address
    ADD CONSTRAINT uc_address_country UNIQUE (country_id);

ALTER TABLE employee
    ADD CONSTRAINT uc_employee_address UNIQUE (address_id);

ALTER TABLE address
    ADD CONSTRAINT FK_ADDRESS_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE country
    ADD CONSTRAINT FK_COUNTRY_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);