CREATE TABLE civility
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code       VARCHAR(255),
    name       VARCHAR(255),
    company_id BIGINT,
    CONSTRAINT pk_civility PRIMARY KEY (id)
);

ALTER TABLE employee
    ADD civility_id BIGINT;

ALTER TABLE employee
    ADD last_name VARCHAR(255);

ALTER TABLE employee
    ADD CONSTRAINT uc_employee_civility UNIQUE (civility_id);

ALTER TABLE civility
    ADD CONSTRAINT FK_CIVILITY_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_CIVILITY FOREIGN KEY (civility_id) REFERENCES civility (id);

ALTER TABLE employee
DROP
COLUMN salary;